services:
  postgres:
    build: ./db
    container_name: red_tetris
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: red_tetris
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    # volumes:
      # - pgdata:/var/lib/postgresql/data

# volumes:
  # pgdata: